[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
# via_ir = true

[rpc_endpoints]
bundler = "http://127.0.0.1:4337"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
